GET https://6mjg4pbord.execute-api.eu-west-1.amazonaws.com/api/numberOfReports HTTP/1.1
content-type: application/json

###

GET https://6mjg4pbord.execute-api.eu-west-1.amazonaws.com/api/numberOfVehicles HTTP/1.1
content-type: application/json

###

GET https://6mjg4pbord.execute-api.eu-west-1.amazonaws.com/api/numberOfAnomalies HTTP/1.1
content-type: application/json